### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by sbendar**
Problem
=======
Update/add Apache 2.0 OSS license [#177840963]https://www.pivotaltracker.com/story/show/177840963)

Solution
========
Add license from github license template

### CODE REVIEW

**Review by wilwade — CHANGES_REQUESTED** [review]
Should the website be CC? It is more content than code?

(Also our package.json needs the license and to remove the private: true flag.)

**Comment by kfogel** [comment]
Yeah, CC-BY-SA is what we've been using for other mostly-non-code repositories.  I think that would make sense here FWIW.  @sbendar, thoughts?

**Comment by sbendar** [comment]
Yep got too aggressive in my license changes.  Does make me think if a sites code is licensed differently than the content.  Not that we would do that here I will delete the.branch.

Apr 21, 2021 7:56:59 AM Karl Fogel ***@***.***>:

**Comment by sbendar** [comment]
Closing and keeping license unchanged.

**Comment by kfogel** [comment]
Cool -- thanks, @sbendar.

**Pull request closed without merging**
